package com.newthread.mapper;

import com.newthread.domain.Farm;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface FarmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String faid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated
     */
    int insert(Farm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated
     */
    Farm selectByPrimaryKey(String faid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated
     */
    List<Farm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Farm record);

    @Select("select faid, fid, name, address, phone, web" +
            "    from farm" +
            "    where fid = #{fid,jdbcType=VARCHAR}")
    List<Farm> selectAllByFid(String fid);
}