package com.newthread.mapper;

import com.newthread.domain.Farmer;
import java.util.List;

public interface FarmerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmer
     *
     * @mbggenerated
     */
    int insert(Farmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmer
     *
     * @mbggenerated
     */
    Farmer selectByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmer
     *
     * @mbggenerated
     */
    List<Farmer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Farmer record);
}