package com.newthread.mapper;

import com.newthread.domain.FarmerReport;
import com.newthread.model.ReportPart;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface FarmerReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmer_report
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String frid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmer_report
     *
     * @mbggenerated
     */
    int insert(FarmerReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmer_report
     *
     * @mbggenerated
     */
    FarmerReport selectByPrimaryKey(String frid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmer_report
     *
     * @mbggenerated
     */
    List<FarmerReport> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmer_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FarmerReport record);

    @Select("select rid,frid, name, 'order' from farmer_report where frid = #{fid}")
    ReportPart selectByFrid(String fid);
}