package com.newthread.mapper;

import com.newthread.domain.ManagerReport;
import java.util.List;

public interface ManagerReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_report
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer mrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_report
     *
     * @mbggenerated
     */
    int insert(ManagerReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_report
     *
     * @mbggenerated
     */
    ManagerReport selectByPrimaryKey(Integer mrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_report
     *
     * @mbggenerated
     */
    List<ManagerReport> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ManagerReport record);

    List<ManagerReport> selectByManagerId(String mrid);
}