package com.newthread.domain;

public class Catalog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.gcpid
     *
     * @mbggenerated
     */
    private String gcpid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column catalog.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbggenerated
     */
    public Catalog(String gcpid, String name) {
        this.gcpid = gcpid;
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catalog
     *
     * @mbggenerated
     */
    public Catalog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.gcpid
     *
     * @return the value of catalog.gcpid
     *
     * @mbggenerated
     */
    public String getGcpid() {
        return gcpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.gcpid
     *
     * @param gcpid the value for catalog.gcpid
     *
     * @mbggenerated
     */
    public void setGcpid(String gcpid) {
        this.gcpid = gcpid == null ? null : gcpid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column catalog.name
     *
     * @return the value of catalog.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column catalog.name
     *
     * @param name the value for catalog.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}