package com.newthread.domain;

public class FarmerReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmer_report.frid
     *
     * @mbggenerated
     */

    private String rid;

    private String frid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmer_report.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmer_report.order
     *
     * @mbggenerated
     */
    private String order;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmer_report
     *
     * @mbggenerated
     */
    public FarmerReport(String frid, String name, String order) {
        this.frid = frid;
        this.name = name;
        this.order = order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmer_report
     *
     * @mbggenerated
     */
    public FarmerReport() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmer_report.frid
     *
     * @return the value of farmer_report.frid
     *
     * @mbggenerated
     */
    public String getFrid() {
        return frid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmer_report.frid
     *
     * @param frid the value for farmer_report.frid
     *
     * @mbggenerated
     */
    public void setFrid(String frid) {
        this.frid = frid == null ? null : frid.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmer_report.name
     *
     * @return the value of farmer_report.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmer_report.name
     *
     * @param name the value for farmer_report.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

}