package com.newthread.domain;

public class Farm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.faid
     *
     * @mbggenerated
     */
    private String faid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.fid
     *
     * @mbggenerated
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farm.web
     *
     * @mbggenerated
     */
    private String web;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated
     */
    public Farm(String faid, String fid, String name, String address, String phone, String web) {
        this.faid = faid;
        this.fid = fid;
        this.name = name;
        this.address = address;
        this.phone = phone;
        this.web = web;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farm
     *
     * @mbggenerated
     */
    public Farm() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.faid
     *
     * @return the value of farm.faid
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.faid
     *
     * @param faid the value for farm.faid
     *
     * @mbggenerated
     */
    public void setFaid(String faid) {
        this.faid = faid == null ? null : faid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.fid
     *
     * @return the value of farm.fid
     *
     * @mbggenerated
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.fid
     *
     * @param fid the value for farm.fid
     *
     * @mbggenerated
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.name
     *
     * @return the value of farm.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.name
     *
     * @param name the value for farm.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.address
     *
     * @return the value of farm.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.address
     *
     * @param address the value for farm.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.phone
     *
     * @return the value of farm.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.phone
     *
     * @param phone the value for farm.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farm.web
     *
     * @return the value of farm.web
     *
     * @mbggenerated
     */
    public String getWeb() {
        return web;
    }

    @Override
    public String toString() {
        return "Farm{" +
                "faid='" + faid + '\'' +
                ", fid='" + fid + '\'' +
                ", name='" + name + '\'' +
                ", address='" + address + '\'' +
                ", phone='" + phone + '\'' +
                ", web='" + web + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farm.web
     *
     * @param web the value for farm.web
     *
     * @mbggenerated
     */
    public void setWeb(String web) {
        this.web = web == null ? null : web.trim();
    }
}