package com.newthread.domain;

public class Farmer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmer.fid
     *
     * @mbggenerated
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmer.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmer.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column farmer.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmer
     *
     * @mbggenerated
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table farmer
     *
     * @mbggenerated
     */
    public Farmer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmer.fid
     *
     * @return the value of farmer.fid
     *
     * @mbggenerated
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmer.fid
     *
     * @param fid the value for farmer.fid
     *
     * @mbggenerated
     */
    public void setFid(String fid) {
        this.fid = fid == null ? null : fid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmer.name
     *
     * @return the value of farmer.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmer.name
     *
     * @param name the value for farmer.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmer.email
     *
     * @return the value of farmer.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmer.email
     *
     * @param email the value for farmer.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column farmer.phone
     *
     * @return the value of farmer.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column farmer.phone
     *
     * @param phone the value for farmer.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public String toString() {
        return "Farmer{" +
                "fid='" + fid + '\'' +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", phone='" + phone + '\'' +
                '}';
    }
}