package com.newthread.domain;

public class ManagerReport {

    public ManagerReport(Integer mrid, String mid, String name, Integer startDate, Integer endDate, String ordersPlaced, String ordersDelivered, String ordersOpen, String ordersCancelled, Double totalRevenue, Double totalProductsRevenue, Double totalDeliveryRevenue, Double lf2uManagementFee, Double totalLf2uFees, Double totalPayableToFarm, String byFarmer) {
        this.mrid = mrid;
        this.mid = mid;
        this.name = name;
        this.startDate = startDate;
        this.endDate = endDate;
        this.ordersPlaced = ordersPlaced;
        this.ordersDelivered = ordersDelivered;
        this.ordersOpen = ordersOpen;
        this.ordersCancelled = ordersCancelled;
        this.totalRevenue = totalRevenue;
        this.totalProductsRevenue = totalProductsRevenue;
        this.totalDeliveryRevenue = totalDeliveryRevenue;
        this.lf2uManagementFee = lf2uManagementFee;
        this.totalLf2uFees = totalLf2uFees;
        this.totalPayableToFarm = totalPayableToFarm;
        this.byFarmer = byFarmer;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.mrid
     *
     * @mbggenerated
     */
    private Integer mrid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.mid
     *
     * @mbggenerated
     */
    private String mid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.start_date
     *
     * @mbggenerated
     */
    private Integer startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.end_date
     *
     * @mbggenerated
     */
    private Integer endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.orders_placed
     *
     * @mbggenerated
     */
    private String ordersPlaced;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.orders_delivered
     *
     * @mbggenerated
     */
    private String ordersDelivered;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.orders_open
     *
     * @mbggenerated
     */
    private String ordersOpen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.orders_cancelled
     *
     * @mbggenerated
     */
    private String ordersCancelled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.total_revenue
     *
     * @mbggenerated
     */
    private Double totalRevenue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.total_products__revenue
     *
     * @mbggenerated
     */
    private Double totalProductsRevenue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.total_delivery_revenue
     *
     * @mbggenerated
     */
    private Double totalDeliveryRevenue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.lf2u_management_fee
     *
     * @mbggenerated
     */
    private Double lf2uManagementFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.total_lf2u_fees
     *
     * @mbggenerated
     */
    private Double totalLf2uFees;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.total_payable_to_farm
     *
     * @mbggenerated
     */
    private Double totalPayableToFarm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager_report.by_farmer
     *
     * @mbggenerated
     */
    private String byFarmer;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_report
     *
     * @mbggenerated
     */

    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_report.mid
     *
     * @param mid the value for manager_report.mid
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_report.name
     *
     * @return the value of manager_report.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_report.name
     *
     * @param name the value for manager_report.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_report.start_date
     *
     * @return the value of manager_report.start_date
     *
     * @mbggenerated
     */
    public String getOrdersPlaced() {
        return ordersPlaced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_report.orders_placed
     *
     * @param ordersPlaced the value for manager_report.orders_placed
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_report.orders_delivered
     *
     * @return the value of manager_report.orders_delivered
     *
     * @mbggenerated
     */
    public String getOrdersDelivered() {
        return ordersDelivered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager_report.orders_delivered
     *
     * @param ordersDelivered the value for manager_report.orders_delivered
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager_report.orders_open
     *
     * @return the value of manager_report.orders_open
     *
     * @mbggenerated
     */
    public String getOrdersOpen() {
        return ordersOpen;
    }

    public String getOrdersCancelled() {
        return ordersCancelled;
    }
}